Repository 42seoul-webserv/webserv, pull requests merged in 2022-11, with the labels that each got.

#18 Feat kqueue 적용된 server
  .gitignore
  CMakeLists.txt
  config/default.conf
  include/Server.hpp
  include/ServerManager.hpp
  include/WebservDefines.hpp
  index.html
  src/Server.cpp
  src/ServerManager.cpp
  src/ServerUtil.cpp
  src/main.cpp
Labels: enhancement, feature

#32 feat : (HTTPResponse) merge source to header
  CMakeLists.txt
  Todo
  include/HttpResponse.hpp
  include/WebservDefines.hpp
  src/HttpResponse.cpp
  src/ServerManager.cpp
  src/ServerUtil.cpp
Labels: feature

#34 Refactor code styles
  CMakeLists.txt
  include/HTTPRequest.hpp
  include/HttpResponse.hpp
  include/Location.hpp
  include/Parser.hpp
  include/RequestParser.hpp
  include/RequestProcessor.hpp
  include/Server.hpp
  include/ServerManager.hpp
  include/WebservDefines.hpp
  src/HttpResponse.cpp
  src/Location.cpp
  src/Parser.cpp
  src/RequestParser.cpp
  src/RequestProcessor.cpp
  src/Server.cpp
  src/ServerManager.cpp
  src/ServerUtil.cpp
  src/main.cpp
Labels: refactor

#47 FEAT: ThreadPool Server
  CMakeLists.txt
  include/ServerManager.hpp
  include/ThreadPool.hpp
  include/WebservDefines.hpp
  src/HTTPResponse.cpp
  src/RequestParser.cpp
  src/RequestProcessor.cpp
  src/Server.cpp
  src/ServerManager.cpp
  src/ServerUtil.cpp
  src/ThreadPool.cpp
Labels: enhancement, feature

#48 Siege에서 재시도 하면 fail 나는거 수정
  include/ServerManager.hpp
  include/WebservDefines.hpp
  src/HTTPResponse.cpp
  src/Server.cpp
  src/ServerUtil.cpp
Labels: fix

#49 enhancement : DEBUG 모드 추가, ThreadPool에서 메인 KQ를 감시해서 필요할 때만 깨워짐
  include/HTTPResponse.hpp
  include/ServerManager.hpp
  include/ThreadPool.hpp
  include/WebservDefines.hpp
  src/HTTPResponse.cpp
  src/RequestProcessor.cpp
  src/Server.cpp
  src/ServerManager.cpp
  src/ServerUtil.cpp
  src/ThreadPool.cpp
Labels: enhancement
